CREATE TABLE EMPLOYEE 
(
  FNAME VARCHAR2(50 BYTE) NOT NULL 
, LNAME VARCHAR2(50 BYTE) NOT NULL 
, DIVISION VARCHAR2(50 BYTE) NOT NULL 
, BUILDING VARCHAR2(50 BYTE) NOT NULL 
, TITLE VARCHAR2(50 BYTE) NOT NULL 
, ROOM VARCHAR2(50 BYTE) NOT NULL 
, ID NUMBER(10, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20 NOT NULL 
, CONSTRAINT EMPLOYEE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMPLOYEE_PK ON EMPLOYEE (ID ASC) 
      LOGGING 
      TABLESPACE SYSTEM 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        FREELISTS 1 
        FREELIST GROUPS 1 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
